blueprint:
  name: Danfoss TRV manual sync (Z2M)
  description: Synchronize the temperature between multiple Danfoss / Popp TRVs when user changes temperature on one of them manually. Relies on entites provided by Zigbee2MQTT.
  domain: automation
  input:
    trvs:
      name: TRVs
      description: The TRVs to synchronize temperature between. At least two entities are required.
      selector:
        entity:
          domain: climate
          multiple: true
trigger:
  - platform: state
    entity_id: !input trvs
    attribute: temperature
condition:
  - condition: template
    value_template: "{{ states('sensor.' + trigger.entity_id.split('.')[-1] + '_setpoint_change_source') == 'manual' }}"
action:
  - repeat:
      for_each: !input trvs
      sequence:
        - if:
            - condition: template
              value_template: "{{ trigger.entity_id != repeat.item }}"
          then:
            - action: climate.set_temperature
              data:
                temperature: "{{ state_attr(trigger.entity_id, 'temperature') }}"
              target:
                entity_id: "{{ repeat.item }}"
mode: single
